export const categories = [
    { value: 'GENERAL_MERCHANDISE', label: 'Mercadorias em Geral' },
    { value: 'CONSUMER_GOODS', label: 'Bens de Consumo' },
    { value: 'DURABLE_GOODS', label: 'Bens Duráveis' },
    { value: 'NON_DURABLE_GOODS', label: 'Bens Não Duráveis' },
    { value: 'PERISHABLES', label: 'Perecíveis' },
    { value: 'NON_PERISHABLES', label: 'Não Perecíveis' },
    { value: 'LUXURY_ITEMS', label: 'Itens de Luxo' },
    { value: 'ESSENTIALS', label: 'Essenciais' },
    { value: 'ELECTRONICS_AND_APPLIANCES', label: 'Eletrônicos e Eletrodomésticos' },
    { value: 'FURNITURE_AND_HOME_DECOR', label: 'Móveis e Decoração' },
    { value: 'CLOTHING_AND_ACCESSORIES', label: 'Roupas e Acessórios' },
    { value: 'TOYS_AND_GAMES', label: 'Brinquedos e Jogos' },
    { value: 'BEAUTY_AND_HEALTH', label: 'Beleza e Saúde' },
    { value: 'SPORTS_AND_OUTDOORS', label: 'Esportes e Atividades ao Ar Livre' },
    { value: 'AUTOMOTIVE_AND_TOOLS', label: 'Automotivos e Ferramentas' },
    { value: 'OFFICE_AND_SCHOOL_SUPPLIES', label: 'Material de Escritório e Escolar' },
    { value: 'PET_CARE', label: 'Cuidados com Animais' },
    { value: 'FOOD_AND_BEVERAGES', label: 'Alimentos e Bebidas' },
    { value: 'ENTERTAINMENT', label: 'Entretenimento' },
    { value: 'OTHER', label: 'Outros' }
];