import "./globals.css";
import "../fonts/fonts.css";
import styles from "./page.module.css";
import { Metadata } from "next";
import ClientProvider from "./ClientProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<ClientProvider>{children}</ClientProvider>
			</body>
		</html>
	);
}
